### ISSUE TITLE
Possible certificate issue with machine-api-provider-nutanix

### ISSUE THREAD

**Issue by tonyjames** [nutanix-cloud-native/machine-api-provider-nutanix#6]
Environment:

Prism Central 2022.4.0.2
AOS 5.20.4.6
OpenShift 4.11.0-rc.6

I'm able to provision an OpenShift cluster only if I mark the masters as schedulable. If the masters are not  schedulable the install process fails because the worker VMs are never created. The issue seems to be with the machine api controller. My Prism Central and Prism Element instances are both using certificates that were issued by my CA. I've added my CA certificate to the install-config.yaml in the `additionalTrustBundle` section but the machine-api-controllers pod is still showing errors like this:

```
E0804 13:18:31.658277       1 controller.go:289] ocp-sb6wr-worker-x4msc: failed to check if machine exists: Error when finding VM by name ocp-sb6wr-worker-x4msc. error: Post "https://prism.tonyjames.lab:9440/api/nutanix/v3/vms/list": x509: certificate signed by unknown authority
```

**Comment by vnephologist** [comment]
Thanks for raising the issue @tonyjames. Unfortunately, this is a retired repo from some of the initial integration work. I will take it down today to avoid future confusion. Could you raise your issue here: https://github.com/openshift/machine-api-provider-nutanix or file a bugzilla? 
cc: @thunderboltsid @yanhua121 for awareness
